Metrics/LineLength:
    Max: 250
Metrics/MethodLength:
    Max: 50
Metrics/AbcSize:
    Max: 40
Metrics/CyclomaticComplexity:
    Max: 10
Metrics/PerceivedComplexity:
    Max: 10
Metrics/ModuleLength:
    Max: 200
Style/FileName:
    Enabled: false
Style/EndOfLine:
    Enabled: false
AllCops:
    Exclude:
      - 'Policyfile.rb'
